- name: Storage Bucket Creation
  hosts: localhost
  connection: local
  become: false
  gather_facts: no

  vars:
    gcp_project: "707747151911"
    gcp_auth_file: "auth.json"
    gcp_region: "europe-west1"
    bucket_name: "ggcd-data"
    dest: ""

  tasks:
    - name: Create storage bucket
      google.cloud.gcp_storage_bucket:
        name: "{{ bucket_name }}"
        location: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_auth_file }}"
        state: present
      tags:
        - create


    - name: Delete storage bucket
      command: gsutil rm -r gs://"{{ bucket_name }}"
      tags:
        - destroy

    - name: Upload file to bucket
      command: gsutil cp -r "{{ src }}" gs://"{{ bucket_name }}"/"{{ dest }}"
      tags:
        - upload

    - name: Download from storage object
      google.cloud.gcp_storage_object:
        action: download
        bucket: "{{ bucket_name }}"
        src: "{{ src }}"
        dest: "{{ dest }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_auth_file }}"
      tags:
        - download

    - name: Download folder from bucket
      command: gsutil cp -r gs://"{{ bucket_name }}"/"{{ src }}" "{{ dest }}"
      tags:
        - download-folder

    - name: Delete from storage object
      google.cloud.gcp_storage_object:
        action: delete
        bucket: "{{ bucket_name }}"
        src: "{{ src }}"
        dest: "{{ dest }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_auth_file }}"
      tags:
        - delete